server:
  port: 9111

spring:
  profiles:
    active: dev
    include:
      - override

  cloud:
    config:
      server:
        git:
          uri: https://github.com/coding-buddha/coding-buddha-private
          timeout: 5
          username: ${git.username:pasudo123}
          password: ${git.password:}
          skip-ssl-validation: true
          force-pull: true
